### ISSUE TITLE
Bitbucket and SPFx development

### ISSUE THREAD

**Issue by mahor1** [pnp/pnp.github.io#21]
Hello all,

I would like please to have your feedback about the usage of bitbucket on SPFx deployment (DevOps)
I started a project and the client has mainly choosen Jira platform for internal IT project.

Does it make sense for SharePoint Development (and deployment) ?

Thanks in advance for your feedback

**Comment by andrewconnell** [comment]
Probably not the best place to ask the question as it has nothing to do with this project. 

With that being said, nothing special about BitBucket that would exclude/include it as a place to keep SPFx projects & implement CI/CD. So... not recommended but also not discouraged.
