### ISSUE TITLE
On mobile the navigation menu does not expand when clicking the hamburger button

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/pnp.github.io#24]
On mobile the navigation menu does not expand when clicking the hamburger button:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/5267487/186853842-f73286f1-ed05-456f-aee0-3bcdac064698.png">

**Comment by martinlingstuyl** [comment]
@hugoabernier, @PopWarner, I think nobody is monitoring this repo. so just highlighting this again at-mentioning you 😁. with mobile usage being high, this is an annoying little bug.

**Comment by hugoabernier** [comment]
lol, you're right, we don't tend to get many notifications from this repo. We'll have to look into this.

**Comment by garrytrinder** [comment]
Just noticed this myself.

I found that the menu works fine if you try it on https://pnp.github.io/docs/

**Comment by PopWarner** [comment]
I believe it's a meta tag. I will test it this weekend. :)

**Comment by Adam-it** [comment]
I'll take it

**Comment by martinlingstuyl** [comment]
You're a hero 🦸
