### ISSUE TITLE
Suggestion: Add Viva Connections Toolkit VS Code extension to Tools section

### ISSUE THREAD

**Issue by Adam-it** [pnp/pnp.github.io#29]
I think it would be really awesome if we could extend the Tools section https://pnp.github.io/#tools with a link to Viva Connection Toolkit VS Code extension https://github.com/pnp/vscode-viva

Seem to be as simple as extending the index.html with a new Tool 
https://github.com/pnp/pnp.github.io/blob/d22638ba2fdfd75cf8f6dccb56283fb34d860b92/index.html#L820

**Comment by Adam-it** [comment]
@PopWarner, @hugoabernier what do you think? Seems legit 😉
if you agree I may open a PR with this change

**Comment by hugoabernier** [comment]
> @PopWarner, @hugoabernier what do you think? Seems legit 😉 if you agree I may open a PR with this change

Yes please go ahead!

**Comment by Adam-it** [comment]
ok @hugoabernier the PR is ready, Cheers 👍
