### ISSUE TITLE
Tools section not logical description 

### ISSUE THREAD

**Issue by Adam-it** [pnp/pnp.github.io#31]
### 🤔 Problem

So checking our community tools section I kinda noticed this does not make sense 
![image](https://github.com/pnp/pnp.github.io/assets/58668583/9beb39c1-b175-4628-919a-f44088390473)
The description clearly states about command line tools and here we have two VS Code extensions 🤦.
Also the 'Visual Studio extension for SharePoint Framework' does not fit this section. 

### 🎯 Aim

This could be solved in two ways:

1.  (the easy way) Just update the Tools section description to something more generic like: "recommended tooling that will boost your productivity" ... or something similar 🤔
2. (the hard way) Leave this section as is, and create a new section for VS and VS Code tooling. 

### 🙋‍♂️

I am willing to work on this

**Comment by Adam-it** [comment]
@PopWarner, @hugoabernier tagging for visibility

**Comment by Adam-it** [comment]
@hugoabernier should I open a PR with a change suggestion? or maybe we want to recheck this on one of our PnP team calls?

**Comment by hugoabernier** [comment]
Go ahead and submit a PR!

Thanks for helping with this

**Comment by Adam-it** [comment]
ok @hugoabernier I opened a PR.
I picked the 2nd option to resolve this issue as IMO it is clearer now and provides more 'space' to extend either the 'Tools' section or (the newly added now) 'Extensions' section. For example in the near (I hope 😜) future we want to introduce the M365 extensions bundle and the PowerPlatform extensions bundle, so those would also be added to the 'Extensions' section
