### ISSUE TITLE
LinkedIn icon has incorrect link

### ISSUE THREAD

**Issue by milanholemans** [pnp/pnp.github.io#48]
Noticed that the LinkedIn icon hyperlink at the bottom of the page points to a non-existing profile.

https://github.com/pnp/pnp.github.io/blob/27a53580232b83b8a17e707321b1f40acd809e52/config/_default/config.toml#L119-L123

**Comment by Adam-it** [comment]
yes, it should be `https://www.linkedin.com/company/m365pnp`. I will fix it up

**Comment by Adam-it** [comment]
Done ✅ 
As soon as cashing refresh new link should be present.
Thanks for pointing it out. You Rock 🤩
