### ISSUE TITLE
Change the Fabio Franzini BlueSky Profile

### ISSUE THREAD

**Issue by fabiofranzini** [pnp/pnp.github.io#50]
Hi @Adam-it, can you replace the URL of my BlueSky profile from 'https://bsky.app/profile/fabiofranzini.bsky.social' to 'https://bsky.app/profile/fabiofranzini.com'?

Thanks in advance! 😄

**Comment by Adam-it** [comment]
> Hi @Adam-it, can you replace the URL of my BlueSky profile from 'https://bsky.app/profile/fabiofranzini.bsky.social' to 'https://bsky.app/profile/fabiofranzini.com'?
> 
> Thanks in advance! 😄 

Sure, will do that today

**Comment by Adam-it** [comment]
done ✅

**Comment by fabiofranzini** [comment]
Thank ❤️
